import { Switch, Route } from "wouter";
import { queryClient } from "@/lib/queryClient";
import { QueryClientProvider } from "@tanstack/react-query";
import { Toaster } from "@/components/ui/toaster";
import { AuthProvider } from "@/hooks/use-auth";
import { TenantProvider } from "@/hooks/use-tenant";
import { ProtectedRoute } from "@/lib/protected-route";
import { useWebSocket } from "@/hooks/useWebSocket";
import { ChatWidget } from "@/components/chatbot/chat-widget";
import NotFound from "@/pages/not-found";
import AuthPage from "@/pages/auth-page";
import DashboardPage from "@/pages/dashboard-page";
import ClientPortalLoginPage from "@/pages/client-portal/login-page";
import ClientPortalDashboardPage from "@/pages/client-portal/dashboard-page";
import ClientPortalEntityDetailPage from "@/pages/client-portal/entity-detail-page";
import ResetPasswordPage from "@/pages/client-portal/reset-password-page";
import ClientsPage from "@/pages/clients-page";
import ClientDetailPage from "@/pages/client-detail-page";
import SetupPage from "@/pages/setup-page";
import TasksPage from "@/pages/tasks-page";
import UsersPage from "@/pages/users-page";
import SettingsPage from "@/pages/settings-page";
import { ComplianceCalendarPage } from "@/pages/compliance-calendar-page";
import AutoGeneratedTasksPage from "@/pages/auto-generated-tasks-page";
import AiReportingPage from "@/pages/ai-reporting-page";
import FinancePage from "@/pages/finance/index";
import CreateInvoicePage from "@/pages/finance/invoices/create";
import CreateInvoiceFromTaskPage from "@/pages/finance/invoices/from-task";
import InvoiceDetailPage from "@/pages/finance/invoices/detail";
import CreatePaymentPage from "@/pages/finance/payments/create";
import CreateChartOfAccountPage from "@/pages/finance/chart-of-accounts/create";
import CreateJournalEntryPage from "@/pages/finance/journal-entries/create";
import EditJournalEntryPage from "@/pages/finance/journal-entries/edit";
import ViewJournalEntryPage from "@/pages/finance/journal-entries/view";
import InvoicePrintPage from "@/pages/finance/invoices/print";
import AccountHeadsManagementPage from "@/pages/finance/account-heads";
import COAConfigurationPage from "@/pages/setup/coa-configuration";
import AiCustomizationPage from "@/pages/setup/ai-customization";
import FinancialReportsPage from "@/pages/finance/reports";
import LedgerReportPage from "@/pages/finance/ledger";
import ProfitAndLossPage from "@/pages/finance/reports/profit-loss";
import BalanceSheetPage from "@/pages/finance/reports/balance-sheet";
import CashFlowPage from "@/pages/finance/reports/cash-flow";
import ExpenseReportPage from "@/pages/finance/reports/expenses";
import TaxSummaryPage from "@/pages/finance/reports/tax-summary";
import JournalEntriesReportPage from "@/pages/finance/reports/journal-entries";

import WorkflowAutomationPage from "@/pages/workflow-automation";
import { NotificationsPage } from "@/pages/notifications-page";

import { EntityDetailPage } from "@/pages/entity-detail";
import ReportsPage from "@/pages/reports/reports-page";
import TaskPerformanceReport from "@/pages/reports/task-performance-report";
import ComplianceOverviewReport from "@/pages/reports/compliance-overview-report";
import TeamEfficiencyReport from "@/pages/reports/team-efficiency-report";
import TaskLifecycleReport from "@/pages/reports/task-lifecycle-report";
import RiskAssessmentReport from "@/pages/reports/risk-assessment-report";
import JurisdictionAnalysisReport from "@/pages/reports/jurisdiction-analysis-report";
import PaymentPage from "@/pages/payment-page";

// SaaS Admin Portal imports
import SaasProtectedRoute from "@/components/saas-admin/saas-protected-route";
import SaasLoginPage from "@/pages/saas-admin/saas-login-page";
import SaasDashboardPage from "@/pages/saas-admin/saas-dashboard-page";
import SaasTenantsPage from "@/pages/saas-admin/saas-tenants-page";
import SaasTenantDetailPage from "@/pages/saas-admin/saas-tenant-detail-page";
import SaasPackagesPage from "@/pages/saas-admin/saas-packages-page";
import SaasBlogPage from "@/pages/saas-admin/saas-blog-page";
import SaasSettingsPage from "@/pages/saas-admin/saas-settings-page";

function Router() {
  return (
    <Switch>
      {/* Main application routes */}
      <ProtectedRoute path="/" component={DashboardPage} />
      <ProtectedRoute path="/clients" component={ClientsPage} />
      <ProtectedRoute path="/clients/:id" component={ClientDetailPage} />
      <ProtectedRoute path="/entities/:entityId" component={EntityDetailPage} />
      <ProtectedRoute path="/setup" component={SetupPage} />
      <ProtectedRoute path="/setup/coa-configuration" component={COAConfigurationPage} />
      <ProtectedRoute path="/setup/ai-customization" component={AiCustomizationPage} />
      <ProtectedRoute path="/tasks" component={TasksPage} />
      <ProtectedRoute path="/tasks/:id" component={TasksPage} />
      <ProtectedRoute path="/auto-generated-tasks" component={AutoGeneratedTasksPage} />
      <ProtectedRoute path="/compliance-calendar" component={ComplianceCalendarPage} />
      <ProtectedRoute path="/ai-reporting" component={AiReportingPage} />
      <ProtectedRoute path="/workflow" component={WorkflowAutomationPage} />
      <ProtectedRoute path="/finance" component={FinancePage} />
      
      {/* Reports routes */}
      <ProtectedRoute path="/reports" component={ReportsPage} />
      <ProtectedRoute path="/reports/task-performance" component={TaskPerformanceReport} />
      <ProtectedRoute path="/reports/compliance-overview" component={ComplianceOverviewReport} />
      <ProtectedRoute path="/reports/team-efficiency" component={TeamEfficiencyReport} />
      <ProtectedRoute path="/reports/task-lifecycle" component={TaskLifecycleReport} />
      <ProtectedRoute path="/reports/risk-assessment" component={RiskAssessmentReport} />
      <ProtectedRoute path="/reports/jurisdiction-analysis" component={JurisdictionAnalysisReport} />
      
      {/* Client Portal routes */}
      <Route path="/client-portal/login" component={ClientPortalLoginPage} />
      <Route path="/client-portal" component={ClientPortalDashboardPage} />
      <Route path="/client-portal/dashboard" component={ClientPortalDashboardPage} />
      <Route path="/client-portal/entities/:id" component={ClientPortalEntityDetailPage} />
      <Route path="/client-portal/reset-password" component={ResetPasswordPage} />
      
      {/* SaaS Admin Portal routes */}
      <Route path="/saas-admin/login" component={SaasLoginPage} />
      <Route path="/saas-admin">
        <SaasProtectedRoute>
          <SaasDashboardPage />
        </SaasProtectedRoute>
      </Route>
      <Route path="/saas-admin/dashboard">
        <SaasProtectedRoute>
          <SaasDashboardPage />
        </SaasProtectedRoute>
      </Route>
      <Route path="/saas-admin/tenants">
        <SaasProtectedRoute>
          <SaasTenantsPage />
        </SaasProtectedRoute>
      </Route>
      <Route path="/saas-admin/tenants/:tenantId">
        <SaasProtectedRoute>
          <SaasTenantDetailPage />
        </SaasProtectedRoute>
      </Route>
      <Route path="/saas-admin/packages">
        <SaasProtectedRoute>
          <SaasPackagesPage />
        </SaasProtectedRoute>
      </Route>
      <Route path="/saas-admin/blog">
        <SaasProtectedRoute>
          <SaasBlogPage />
        </SaasProtectedRoute>
      </Route>
      <Route path="/saas-admin/settings">
        <SaasProtectedRoute>
          <SaasSettingsPage />
        </SaasProtectedRoute>
      </Route>

      {/* Public payment routes */}
      <Route path="/pay/:invoiceId" component={PaymentPage} />
      <Route path="/payment/:invoiceId" component={PaymentPage} />
      {/* Direct invoice creation disabled - invoices are now created only through tasks */}
      {/* <ProtectedRoute path="/finance/invoices/create" component={CreateInvoicePage} /> */}
      <ProtectedRoute path="/finance/invoices/from-task" component={CreateInvoiceFromTaskPage} />
      <ProtectedRoute path="/finance/invoices/:id/print" component={InvoicePrintPage} />
      <ProtectedRoute path="/finance/invoices/:tenantId/:invoiceNumber" component={InvoiceDetailPage} />
      <ProtectedRoute path="/finance/payments/create" component={CreatePaymentPage} />
      <ProtectedRoute path="/finance/account-heads" component={AccountHeadsManagementPage} />
      <ProtectedRoute path="/finance/chart-of-accounts/create" component={CreateChartOfAccountPage} />
      <ProtectedRoute path="/finance/journal-entries/create" component={CreateJournalEntryPage} />
      <ProtectedRoute path="/finance/journal-entries/edit/:id" component={EditJournalEntryPage} />
      <ProtectedRoute path="/finance/journal-entries/view/:id" component={ViewJournalEntryPage} />
      <ProtectedRoute path="/finance/reports" component={FinancialReportsPage} />
      <ProtectedRoute path="/finance/ledger" component={LedgerReportPage} />
      <ProtectedRoute path="/finance/reports/journal-entries" component={JournalEntriesReportPage} />
      <ProtectedRoute path="/finance/reports/profit-loss" component={ProfitAndLossPage} />
      <ProtectedRoute path="/finance/reports/balance-sheet" component={BalanceSheetPage} />
      <ProtectedRoute path="/finance/reports/cash-flow" component={CashFlowPage} />
      <ProtectedRoute path="/finance/reports/expenses" component={ExpenseReportPage} />
      <ProtectedRoute path="/finance/reports/tax-summary" component={TaxSummaryPage} />

      <ProtectedRoute path="/users" component={UsersPage} />
      <ProtectedRoute path="/users/:id/permissions" component={UsersPage} />
      <ProtectedRoute path="/settings" component={SettingsPage} />
      <ProtectedRoute path="/notifications" component={NotificationsPage} />

      <Route path="/auth" component={AuthPage} />
      <Route path="/login" component={AuthPage} />
      <Route component={NotFound} />
    </Switch>
  );
}

function AppContent() {
  // Initialize WebSocket connection for real-time notifications
  useWebSocket();
  
  return (
    <>
      <Router />
      <ChatWidget />
      <Toaster />
    </>
  );
}

function App() {
  return (
    <QueryClientProvider client={queryClient}>
      <AuthProvider>
        <TenantProvider>
          <AppContent />
        </TenantProvider>
      </AuthProvider>
    </QueryClientProvider>
  );
}

export default App;
