import { Switch, Route } from "wouter";
import { queryClient } from "@/lib/queryClient";
import { QueryClientProvider } from "@tanstack/react-query";
import { Toaster } from "@/components/ui/toaster";
import { AuthProvider } from "@/hooks/use-auth";
import { ProtectedRoute } from "@/lib/protected-route";
import NotFound from "@/pages/not-found";
import AuthPage from "@/pages/auth-page";
import DashboardPage from "@/pages/dashboard-page";
import ClientsPage from "@/pages/clients-page";
import ClientDetailPage from "@/pages/client-detail-page";
import SetupPage from "@/pages/setup-page";
import TasksPage from "@/pages/tasks-page";
import UsersPage from "@/pages/users-page";
import { ComplianceCalendarPage } from "@/pages/compliance-calendar-page";
import AutoGeneratedTasksPage from "@/pages/auto-generated-tasks-page";
import FinancePage from "@/pages/finance";
import CreateInvoicePage from "@/pages/finance/invoices/create";
import CreateInvoiceFromTaskPage from "@/pages/finance/invoices/from-task";
import CreatePaymentPage from "@/pages/finance/payments/create";
import CreateChartOfAccountPage from "@/pages/finance/chart-of-accounts/create";
import CreateJournalEntryPage from "@/pages/finance/journal-entries/create";
import COAConfigurationPage from "@/pages/setup/coa-configuration";

function Router() {
  return (
    <Switch>
      <ProtectedRoute path="/" component={DashboardPage} />
      <ProtectedRoute path="/clients" component={ClientsPage} />
      <ProtectedRoute path="/clients/:id" component={ClientDetailPage} />
      <ProtectedRoute path="/setup" component={SetupPage} />
      <ProtectedRoute path="/setup/coa-configuration" component={COAConfigurationPage} />
      <ProtectedRoute path="/tasks" component={TasksPage} />
      <ProtectedRoute path="/auto-generated-tasks" component={AutoGeneratedTasksPage} />
      <ProtectedRoute path="/compliance-calendar" component={ComplianceCalendarPage} />
      <ProtectedRoute path="/finance" component={FinancePage} />
      <ProtectedRoute path="/finance/invoices/create" component={CreateInvoicePage} />
      <ProtectedRoute path="/finance/invoices/from-task" component={CreateInvoiceFromTaskPage} />
      <ProtectedRoute path="/finance/payments/create" component={CreatePaymentPage} />
      <ProtectedRoute path="/finance/chart-of-accounts/create" component={CreateChartOfAccountPage} />
      <ProtectedRoute path="/finance/journal-entries/create" component={CreateJournalEntryPage} />
      <ProtectedRoute path="/users" component={UsersPage} />
      <Route path="/auth" component={AuthPage} />
      <Route component={NotFound} />
    </Switch>
  );
}

function App() {
  return (
    <QueryClientProvider client={queryClient}>
      <AuthProvider>
        <Router />
        <Toaster />
      </AuthProvider>
    </QueryClientProvider>
  );
}

export default App;
