import { useState } from "react";
import { AppLayout } from "@/components/layout/app-layout";
import { AutoGeneratedTasksList } from "@/components/tasks/auto-generated-tasks-list";
import { AutoGeneratedTaskHistory } from "@/components/tasks/auto-generated-task-history";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { UserPlus, History, Box, RefreshCw } from "lucide-react";

export default function AutoGeneratedTasksPage() {
  const [activeTab, setActiveTab] = useState<string>("pending");

  return (
    <AppLayout title="Auto Generated Tasks">
      <div className="space-y-4">
        <Tabs 
          defaultValue="pending" 
          value={activeTab} 
          onValueChange={setActiveTab}
          className="w-full"
        >
          <TabsList className="grid w-full grid-cols-2 mb-4">
            <TabsTrigger value="pending" className="flex items-center">
              <Box className="mr-2 h-4 w-4" />
              Pending Approval
            </TabsTrigger>
            <TabsTrigger value="history" className="flex items-center">
              <History className="mr-2 h-4 w-4" />
              History
            </TabsTrigger>
          </TabsList>
          
          <TabsContent value="pending" className="mt-0">
            <AutoGeneratedTasksList />
          </TabsContent>
          
          <TabsContent value="history" className="mt-0">
            <AutoGeneratedTaskHistory />
          </TabsContent>
        </Tabs>
      </div>
    </AppLayout>
  );
}