import { AppLayout } from "@/components/layout/app-layout";
import { AutoGeneratedTasksList } from "@/components/tasks/auto-generated-tasks-list";

export default function AutoGeneratedTasksPage() {
  return (
    <AppLayout title="Auto Generated Tasks">
      <AutoGeneratedTasksList />
    </AppLayout>
  );
}